apiVersion: v1
kind: Pod
metadata:
  name: bad-privileged-pod
  namespace: audit-zone
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      privileged: true # ЗАПРЕЩЕНО в restricted
