@startmindmap
* Безопасность данных PropDevelopment

** Публичные данные
***_ Данные о планировках квартир
***_ Рекламные материалы
***_ Адреса офисов
**** Риск: Искажение данных (Defacement)
***** Вероятность: Средняя
***** Ущерб: Репутационный (Низкий)

** Внутренние данные (Internal)
***_ ???
***_ ???

** Конфиденциальные данные (Confidential)
***_ ???
**** Риск: ???

** Секретные данные (Secret)
***_ ???
@endmindmap