apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # Логируем тело запроса для критичных изменений (создание подов, доступ к секретам)
  - level: RequestResponse
    verbs: ["create", "delete", "update", "patch"]
    resources:
    - group: ""
      resources: ["pods", "secrets", "configmaps", "serviceaccounts"]
    - group: "rbac.authorization.k8s.io"
      resources: ["roles", "rolebindings"]

  # Логируем метаданные для доступа к секретам (кто читал?)
  - level: Metadata
    verbs: ["get", "list"]
    resources:
    - group: ""
      resources: ["secrets"]

  # Для всего остального логируем только метаданные
  - level: Metadata
    omitStages:
      - "RequestReceived"
